### ISSUE TITLE
Output devices gets affected everytime the plugin is turned on

### ISSUE THREAD

**Issue by majedbawarshi** [IniasP/rnnoise-cli#7]
I have noticed that when activating the plugin and tend to use the mic, when I open ubuntu settings and check the sound settings, whenever I speak The indicator of the mic as well as the indicator of sound both show the same percentage of sound...
How would I stop the mic sound indication from affecting the output devices?? 
Thank you so much for your help,

**Comment by IniasP** [comment]
I don't use GNOME, so I don't know what indicator you are talking about. As I mentioned in your other issue (#6), two sinks are created and they are necessary. I know that in KDE Plasma they both show up as "Playback Devices", where one "plays" the normal microphone input and the other the denoised audio (although with separate sound indicators). This makes sense, but I can imagine GNOME settings is trying to simplify by combining all sinks into a single "speaker" indicator, which includes these sinks. I don't think there's a way to stop that, but it shouldn't affect your experience besides that indicator. Again, I don't use GNOME, but this looks like a side effect of having those necessary sinks.

**Comment by majedbawarshi** [comment]
![sound](https://user-images.githubusercontent.com/23002135/153181864-9fae8593-de29-47e6-acdc-043655a1e7f9.png)
Here's what I mean about mic and speaker sound indication. I think the sinks are affecting the other speaker devices as you have mentioned.
Is there any way to stop the sinks from affecting the other speaker devices?

**Comment by IniasP** [comment]
It should not actually be interfering with unrelated output devices, I don't see how that would be possible. Is it just that indicator or are you actually hearing the microphone input through that output?

**Comment by majedbawarshi** [comment]
When I use rnnoise-cli package I don't hear my sound back, I can only see that the indicator of the output is getting higher whenever I speak.
One thing to note is in other LADSPA model handlers like [this one](https://github.com/lawl/NoiseTorch), I used to hear my voice back from the speaker when I use their package provided virtual mic.

**Comment by majedbawarshi** [comment]
Also, I would like to mention that sometimes, after a while of using the plugin, the output devices get affected and no output sound would be given.

**Comment by IniasP** [comment]
> Also, I would like to mention that sometimes, after a while of using the plugin, the output devices get affected and no output sound would be given.

I haven't encountered that myself, but as long as the same pulse modules are still loaded, that seems like something out of the scope of this project. It may be due to the [plugin](https://github.com/werman/noise-suppression-for-voice) itself or pulseaudio or some system-level thing, I really can't say.

I don't think there is anything here that I could possibly resolve in this application, so I'm closing.
